{"startPoint":{"x":126,"y":118,"heading":"linear","startDeg":90,"endDeg":180},"lines":[
{"name":"RedGoalToScore","endPoint":{"x":86,"y":86,"heading":"linear","startDeg":150,"endDeg":0},"controlPoints":[],"color":"#78CDD7"},
{"name":"ScoreToPickup1","endPoint":{"x":108,"y":84,"heading":"linear","reverse":false,"endDeg":0,"startDeg":0},"controlPoints":[],"color":"#DCB995"},
{"name":"Pickup1ToEnd","endPoint":{"x":122,"y":84,"heading":"linear","reverse":false,"startDeg":0,"endDeg":0},"controlPoints":[],"color":"#5C9BC5"},
{"name":"ScoreToPickup2","endPoint":{"x":108,"y":60,"heading":"linear","reverse":false,"startDeg":0,"endDeg":0},"controlPoints":[],"color":"#6B8899"},
{"name":"Pickup2ToEnd","endPoint":{"x":122,"y":60,"heading":"linear","reverse":false,"startDeg":0,"endDeg":0},"controlPoints":[],"color":"#DC9CCD"},
{"name":"ScoreToPickup3","endPoint":{"x":108,"y":36,"heading":"linear","reverse":false,"startDeg":0,"endDeg":0},"controlPoints":[],"color":"#A5AD5D"},
{"name":"Pickup3ToEnd","endPoint":{"x":122,"y":36,"heading":"linear","reverse":false,"startDeg":0,"endDeg":0},"controlPoints":[],"color":"#A9D9B6"},
{"name":"RedTriangleStartPose","endPoint":{"x":85,"y":9,"heading":"linear","reverse":false,"startDeg":0,"endDeg":100},"controlPoints":[],"color":"#56A8A8"},
{"name":"RedTriangleToScore","endPoint":{"x":87,"y":14,"heading":"linear","reverse":false,"startDeg":0,"endDeg":65},"controlPoints":[],"color":"#CC7C9D"}]}